
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javapp
  template:
    metadata:
      labels:
        app: javapp
    spec:
      containers:
        - name: javapp-container
          image: javapp:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: javapp-service
spec:
  selector:
    app: javapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
